### ISSUE TITLE
Return more informative error on retrieve_near with invalid nearId

### ISSUE THREAD

**Issue by ewilz** [near/near-evm#42]
When passed in an invalid near ID (i.e. with capital letters) web3 is returned this the following error. Can do a check in web3, but thought perhaps the contract itself should have an informative error.

```      
ActionError: {"index":0}
          at Object.parseRpcError (/Users/emilywilliams/code/summa/near/near-web3-provider/node_modules/near-api-js/lib/utils/rpc_errors.js:38:19)
          at Account.signAndSendTransaction (/Users/emilywilliams/code/summa/near/near-web3-provider/node_modules/near-api-js/lib/account.js:115:36)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
          at NearProvider.routeEthRetrieveNear (/Users/emilywilliams/code/summa/near/near-web3-provider/src/index.js:741:27) {
        type: 'ActionError',
        index: 0
      }
```

**Comment by ilblackdragon** [comment]
Outdated.
